# Generated by Django 3.2.5 on 2022-04-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
